{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"module4.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyPXiqp2iBIA4ZUw12WFvwJw"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":13,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"EOFzQhq3M3Ve","executionInfo":{"status":"ok","timestamp":1658784301244,"user_tz":420,"elapsed":801,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"b46d4349-b59b-46b9-f3f4-a99b47c3b520"},"outputs":[{"output_type":"stream","name":"stdout","text":["h\n","e\n","l\n","l\n","o\n"," \n","w\n","o\n","r\n","d\n"," \n","i\n","s\n"," \n","t\n","h\n","e\n"," \n","f\n","i\n","n\n","a\n","l\n"," \n"]}],"source":["#Write a python program to find the longest words.\n","file_obj = \"hello word is the final \"\n","\n","for i in file_obj:\n","  if len(max(i)):\n","    print(i)\n","\n"]},{"cell_type":"code","source":["#Write a Python program to count the number of lines in a text file.\n","file_obj = open(\"abc.txt\",\"x\")\n","file_obj.write(\"this is the paregraph \")\n","file_obj.close()"],"metadata":{"id":"K9XUcZDqNXXY","executionInfo":{"status":"ok","timestamp":1658785910322,"user_tz":420,"elapsed":7,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}}},"execution_count":37,"outputs":[]},{"cell_type":"code","source":[""],"metadata":{"id":"40gmB2bWQmO3"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["c = input(\"enter the file name\")\n","fb =  open(\"abc.txt\")\n","for i in fb:\n","  print(i.count(\"\"))"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"lFmZi5HWR3RC","executionInfo":{"status":"ok","timestamp":1658787405786,"user_tz":420,"elapsed":8500,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"c4a647a2-feeb-4092-90aa-643e514e5ce6"},"execution_count":55,"outputs":[{"output_type":"stream","name":"stdout","text":["enter the file nameabc.txt\n","23\n"]}]},{"cell_type":"code","source":["\n","#Write a Python program to count the frequency of words in a file.\n","counter = input(\"enter the file name\")\n","fb = open(\"abc.txt\")\n","counts = dict()\n","for i in fb:\n","  words = i.split()\n","  for word in words:\n","    if word in counts:\n","      counts[word] += 1\n","    else:\n","      counts[word] = 1\n","print(counts)\n","\n","\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"WdSJpkueTznV","executionInfo":{"status":"ok","timestamp":1658786591521,"user_tz":420,"elapsed":6977,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"483e7be2-7d9a-4f20-f864-1d06ba5d2009"},"execution_count":44,"outputs":[{"output_type":"stream","name":"stdout","text":["enter the file nameabc.txt\n","{'this': 1, 'is': 1, 'the': 1, 'paregraph': 1}\n"]}]},{"cell_type":"code","source":["#Write a Python program to copy the contents of a file to another file.\n","r = open(\"abc.txt\" , \"r\")\n","t = open(\"second.txt\" , \"a\")\n","for i in r:\n","  t.write(i)\n","t = open(\"second.txt\")\n","t.read()\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"A1hIg-c4WHPs","executionInfo":{"status":"ok","timestamp":1658788126877,"user_tz":420,"elapsed":10,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"0805e43c-3b21-43c6-fbb3-7e44dd1ffc96"},"execution_count":70,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'this is the paregraph this is the paregraph this is the paregraph '"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":70}]},{"cell_type":"code","source":["#Explain Exception handling? What is an Error in Python?\n","'''An Exception is an error that happens during the execution of a program. Whenever there is an error, Python generates an exception that could be handled. It basically prevents the program from getting crashed'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":53},"id":"3C4AUalLaa43","executionInfo":{"status":"ok","timestamp":1658788216890,"user_tz":420,"elapsed":723,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"5f862b5f-90bd-408a-f4ac-9e505337f21a"},"execution_count":71,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'An Exception is an error that happens during the execution of a program. Whenever there is an error, Python generates an exception that could be handled. It basically prevents the program from getting crashed'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":71}]},{"cell_type":"code","source":["#How many except statements can a try-except block have? Name Some built-in exception classes:\n","'''There has to be at least one except statement.'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"ED1Daem3afdl","executionInfo":{"status":"ok","timestamp":1658788309539,"user_tz":420,"elapsed":43,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"ff46fe75-8073-4bf4-dabd-367d4ef90524"},"execution_count":73,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'There has to be at least one except statement.'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":73}]},{"cell_type":"code","source":["#When will the else part of try-except-else be executed?\n","''' The else part is executed when no exception occurs. 3.'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"eCsLs74JfKUi","executionInfo":{"status":"ok","timestamp":1658788402180,"user_tz":420,"elapsed":1941,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"9430c228-96ac-4472-e0ce-2dc5e8ff2cb2"},"execution_count":74,"outputs":[{"output_type":"execute_result","data":{"text/plain":["' The else part is executed when no exception occurs. 3.'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":74}]},{"cell_type":"code","source":["#Can one block of except statements handle multiple exception?\n","'''Each type of exception can be specified directly.'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"O5KmyYhsfkVm","executionInfo":{"status":"ok","timestamp":1658788458946,"user_tz":420,"elapsed":1729,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"183234da-34e6-4a0e-d735-69539414f14d"},"execution_count":75,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'Each type of exception can be specified directly.'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":75}]},{"cell_type":"code","source":["#When is the finally block executed?\n","'''The finally block always executes when the try block exits. This ensures that the finally block is executed even if an unexpected exception occurs.'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"CvBl1w09fyPk","executionInfo":{"status":"ok","timestamp":1658788668508,"user_tz":420,"elapsed":6609,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"519ffc12-8280-4288-d9aa-58f6c1bcf382"},"execution_count":76,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'The finally block always executes when the try block exits. This ensures that the finally block is executed even if an unexpected exception occurs.'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":76}]},{"cell_type":"code","source":["#What happens when „1‟== 1 is executed?\n","'''it simply evaluates to false and does not raise any exception.'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"_oZxHLubgVKc","executionInfo":{"status":"ok","timestamp":1658789227125,"user_tz":420,"elapsed":21,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"a6ea022b-69b6-4f88-e6cc-83e91e2a62f7"},"execution_count":80,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'it simply evaluates to false and does not raise any exception.'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":80}]},{"cell_type":"code","source":["#How Do You Handle Exceptions With Try/Except/Finally In Python? Explain with coding snippets.\n","print(\"before\")\n","\n","try:\n","  print(city)\n","except:\n","  print(\"this is execute\")\n","finally:\n","  print(\"executing timing\")\n","\n","print(\"after\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"hCp79Wzqg5eB","executionInfo":{"status":"ok","timestamp":1658789453083,"user_tz":420,"elapsed":431,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"54c25ceb-08ae-4e86-85e5-d7f2ac629f4a"},"execution_count":85,"outputs":[{"output_type":"stream","name":"stdout","text":["before\n","this is execute\n","executing timing\n","after\n"]}]},{"cell_type":"code","source":["#Write python program that user to enter only odd numbers, else will raise an exception.\n","num = int(input(\"enter the number\"))\n","mod = num % 2\n","if mod > 0:#\n","  print(\"odd number\")\n","else:\n","  print(\"even number\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"oomzLL5Jh_d5","executionInfo":{"status":"ok","timestamp":1658789679231,"user_tz":420,"elapsed":4173,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"6c328749-8157-4819-9339-60a75b9fceec"},"execution_count":87,"outputs":[{"output_type":"stream","name":"stdout","text":["enter the number2\n","even number\n"]}]},{"cell_type":"code","source":["#What are oops concepts? Is multiple inheritance supported in java\n","'''Multiple Inheritance is a feature of an object-oriented concept, where a class can inherit properties of more than one parent class. The problem occurs when there exist methods with the same signature in both the superclasses and subclass\n","'''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":53},"id":"BfVInw0CkUqc","executionInfo":{"status":"ok","timestamp":1658789761145,"user_tz":420,"elapsed":574,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"206f1b94-3799-4f86-d9a2-83a2dcd48db8"},"execution_count":88,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'Multiple Inheritance is a feature of an object-oriented concept, where a class can inherit properties of more than one parent class. The problem occurs when there exist methods with the same signature in both the superclasses and subclass\\n'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":88}]},{"cell_type":"code","source":["#How to Define a Class in Python? What Is Self? Give An Example Of A Python Class\n","'''Class is a collection of member variables and member methods. A Class just like a template, design or blueprint.\n","self = (self parameter is a reference to the current object of a class. It's used to access variables that belongs to the class.)'''\n","class HelloClass:\n","  def __init__(self):\n","    name = 'hello class'\n","    print('constructor called')\n"],"metadata":{"id":"SsvFdaaBkwso","executionInfo":{"status":"ok","timestamp":1658790155700,"user_tz":420,"elapsed":435,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}}},"execution_count":92,"outputs":[]},{"cell_type":"code","source":["#Write a Python class named Rectangle constructed by a length and width and a method which will compute the area of a rectangle\n","class Rectangle():\n","    def __init__(self, l, w):\n","        self.length = l\n","        self.width  = w\n","\n","    def rectangle_area(self):\n","        return self.length*self.width\n","\n","newRectangle = Rectangle(12,10)\n","print(newRectangle.rectangle_area())"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"0ji-xoHAlYz7","executionInfo":{"status":"ok","timestamp":1658790293969,"user_tz":420,"elapsed":492,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"c63710d3-2ce1-4ad8-8ea9-82d7f9e8ce63"},"execution_count":93,"outputs":[{"output_type":"stream","name":"stdout","text":["120\n"]}]},{"cell_type":"code","source":["#Write a Python class named Circle constructed by a radius and two methods which will compute the area and the perimeter of a circle\n","class circle():\n","  def __init__(self,r):\n","    self.redius = r\n","  def area(self):\n","    return self.redius**2*3.14\n","  def parameter(self):\n","    return self.redius*3.14\n","new_circle = circle(8)\n","print(new_circle.area())\n","print(new_circle.parameter())"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"iJuddpAUmypZ","executionInfo":{"status":"ok","timestamp":1658790633796,"user_tz":420,"elapsed":619,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"5135d890-7342-4645-b270-a8dafc4fa59c"},"execution_count":94,"outputs":[{"output_type":"stream","name":"stdout","text":["200.96\n","25.12\n"]}]},{"cell_type":"code","source":["#What is Instantiation in terms of OOP terminology?\n","'''the processes of creating a new object for a class using a new keyword.'''\n","\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":35},"id":"ClWRYItvoFk-","executionInfo":{"status":"ok","timestamp":1658790885215,"user_tz":420,"elapsed":475,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"27d8ff1a-a0c7-4691-f783-c8966601424c"},"execution_count":95,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'the processes of creating a new object for a class using a new keyword.'"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":95}]},{"cell_type":"code","source":["#What is used to check whether an object o is an instance of class A?\n","'''Using isinstance() function, we can test whether an object/variable is an instance of the specified type or class such as int or list. In the case of inheritance, we can checks if the specified class is the parent class of an object. For example, isinstance(x, int) to check if x is an instance of a class int '''"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":53},"id":"CkbIayrjpDIy","executionInfo":{"status":"ok","timestamp":1658790954175,"user_tz":420,"elapsed":643,"user":{"displayName":"19-BCA-035 [ Roman pateliya ]","userId":"12091278356303165738"}},"outputId":"782cce7c-75cd-49d8-d79a-73f814575e67"},"execution_count":96,"outputs":[{"output_type":"execute_result","data":{"text/plain":["'Using isinstance() function, we can test whether an object/variable is an instance of the specified type or class such as int or list. In the case of inheritance, we can checks if the specified class is the parent class of an object. For example, isinstance(x, int) to check if x is an instance of a class int '"],"application/vnd.google.colaboratory.intrinsic+json":{"type":"string"}},"metadata":{},"execution_count":96}]},{"cell_type":"code","source":[""],"metadata":{"id":"GcwVmTuPpT4q"},"execution_count":null,"outputs":[]}]}